{% set version = "0.7.0" %}

package:
  name: cligj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cligj/cligj-{{ version }}.tar.gz
  sha256: 2bf2042a81be581d707f726aef5efbbd935a62af85d5521305026dabeb798f5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
    - click >=4.0
  run:
    - python
    - click >=4.0

test:
  imports:
    - cligj

about:
  home: https://github.com/mapbox/cligj
  license: BSD 3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Click params for commmand line interfaces to GeoJSON.

extra:
  recipe-maintainers:
    - ocefpaf
