travis:
  secure:
    BINSTAR_TOKEN: nXL6LcB+FPNrit8+8xm/x9NHJejjo9HFeV4PTrWHVBm9XP6dFHznQagjC2v2AXy1XhJzM2gCtqjAhAsRiuaJOSCb2lT6zdASsJ92bbVDESuJcz20Ph+/HcTqIl0uO9grsEUAQio3VYiYh5wck8NdTD7AZ3JoD9TSlS6g9UgeDij17pYyEKNNkdjPEpohAfIVwvNyRdjX37WyRW84k+TSZmEkpAnmbfpK5irzx5TtQ+CFLZtz+KojnhxSh1MQH/IgVlL+HxssMV1FPTiifXXkkMinHBZMD+JCwND8oLNEffw+GW/arvpGsE9TuLATbwmj2OEIFIDLQmRu85XVgU3d1LoUSe1kmKk8F33XVePQcGQ8gV2nFrMEWR/zoz2IN4J83MV9jN5HFg9Z/NmAvo/o6caDqvnQ8JZBdIzCTn8S2QlQhQ8ibE2JuSFd3PXZWnD4mj3rVdIJYIYprlJKbvOHPEuM6X0XtZl3ihqsCaaDMHvuD/z9BrjRNlwyuMka0PoXNZLffIBdH4IhtymUfoI+jkXLjypBqXc7S29wGs9zLKM6wrCssOVHkUfgkpLJSuJQx8wD2EOGWcQ/slK9Dh2y5p0WStSW2aXHzZvbXXCPqtRSSu7n10aCcC073c3fFn8i3wYrE047sUkoDVrtXLXgkr8bqto+HG0GGiaiWv+7MnM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
